/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./src/**/*.{html,js}'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '968px',
      xl: '1100px',
    },
    fontSize: {
      sm: '13px',
      md: '15px',
      lg: '16px',
      h4: '14px',
      h3: '18px',
      h2: '20px',
      h1: '24px',
    },
    lineHeight: {
      sm: '19px',
      md: '22px',
      lg: '23px',
      h4: '20px',
      h3: '26px',
      h2: '29px',
      h1: '35px',
    },
    extend: {
      colors: {
        purple: '#AD1FEA',
        blue: 'hsl(230,76%,59%)',
        darkBlue1: 'hsl(230,31%,31%)',
        darkBlue2: 'hsl(231,33%,34%)',
        white: 'hsl(0,0%,100%)',
        lightGrey1: 'hsl(231,100%,97%)',
        lightGrey2: 'hsl(231,60%,98%)',
        greyishBlue: 'hsl(244,20%,49%)',
        orange: 'hsl(14,83%,74%)',
        lightBlue: 'hsl(204,94%,68%)',
        veryLightBlue: 'rgba(58, 67, 116,0.15)',
        red: '#D73737',
        shade: 'rgba(0,0,0,0.3)',
        grey: '#979797',
      },
      backgroundImage: {
        banner:
          "url('/public/assets/suggestions/desktop/background-header.png')",
        bannerTablet:
          "url('/public/assets/suggestions/tablet/background-header.png')",
        bannerMobile:
          "url('/public/assets/suggestions/mobile/background-header.png')",
      },
      padding: {
        card: '24px',
        pageTop: '70px',
        pageTopTablet: '56px',
      },
      spacing: {
        h4: '-0.2em',
        h3: '-0.25em',
        h2: '-0.25em',
        h1: '-0.33em',
      },
      borderRadius: {
        banner: '12px',
        tag: '8px',
        button: '10px',
        card: '10px',
        textarea: '5px',
        dropdownList: '5px',
      },
      width: {
        banner: '255px',
        bannerTablet: '223px',
        header: '976px',
        footer: '976px',
        button: '158px',
        dropdownList: '255px',
        homepage: '1110px',
        profile: '40px',
        replyTextarea: '461px',
        loginInput: '300px',
        upvoteBtn: '40px',
        upvoteBtnHorizontal: '69px',
        suggestionBoard: '825px',
        suggestionBoardTablet: '689px',
        suggestionBoardMobile: '327px',
        suggestionDetailPage: '730px',
        suggestionDetailPageTablet: '689px',
        suggestionDetailPageMobile: '327px',
        newFeedback: '540px',
        newFeedbackMobile: '327px',
        roadmap: '1110px',
        roadmapTablet: '689px',
        roadmapMobile: '327px',
        sidebarMobile: '271px',
      },
      height: {
        tag: '30px',
        suggestionBoardTopBar: '72px',
        suggestionCard: '151px',
        suggestionCardMobile: '200px',
        button: '44px',
        upvoteBtn: '53px',
        upvoteBtnHorizontal: '50px',
        profile: '40px',
        replyTextarea: '80px',
        commentTextarea: '100px',
        dropdownList: '48px',
        newFeedbackTextarea: '96px',
        roadmapTopBar: '113px',
        roadmapTopBarMobile: '100px',
        roadmapGridColumnCard: '272px',
        homeSideBarCard: '178px',
        bannerMobile: '72px',
        noFeedback: '600px',
        noFeedbackMobile: '460px',
      },
      dropShadow: {
        dropdownList: '0px 7px 10px rgba(0, 0, 0, 0.2)',
      },
      inset: {
        sidebarMobile: '72px',
      },
    },
  },
  plugins: [],
};
